-- Preparacao aditiva para multiplas congregacoes (etapa 1).
-- Esta migracao nao remove colunas, nao altera IDs existentes e nao move dados.

begin;

alter table public.congregacoes
  add column if not exists numero_oficial text,
  add column if not exists slug_publico text,
  add column if not exists status_cadastro text not null default 'aguardando_aprovacao',
  add column if not exists pais text not null default 'Brasil',
  add column if not exists estado_uf text,
  add column if not exists administrador_responsavel_id bigint,
  add column if not exists aprovado_em timestamptz,
  add column if not exists aprovado_por uuid,
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'congregacoes_status_cadastro_check'
      and conrelid = 'public.congregacoes'::regclass
  ) then
    alter table public.congregacoes
      add constraint congregacoes_status_cadastro_check
      check (status_cadastro in ('aguardando_aprovacao', 'aprovada', 'suspensa'));
  end if;
end
$$;

create unique index if not exists congregacoes_numero_oficial_unique
  on public.congregacoes (numero_oficial)
  where numero_oficial is not null;

create unique index if not exists congregacoes_slug_publico_unique
  on public.congregacoes (slug_publico)
  where slug_publico is not null;

update public.congregacoes
set slug_publico = concat(
  trim(both '-' from regexp_replace(
    lower(translate(nome, 'áàâãäéèêëíìîïóòôõöúùûüç', 'aaaaaeeeeiiiiooooouuuuc')),
    '[^a-z0-9]+',
    '-',
    'g'
  )),
  '-',
  id
)
where slug_publico is null;

-- As congregacoes que ja operavam antes desta migracao permanecem ativas.
update public.congregacoes
set
  status_cadastro = 'aprovada',
  aprovado_em = coalesce(aprovado_em, now()),
  updated_at = now()
where ativa = true
  and status_cadastro = 'aguardando_aprovacao';

alter table public.cidades
  add column if not exists codigo_ibge text,
  add column if not exists estado_uf text,
  add column if not exists fonte_oficial text,
  add column if not exists atualizado_fonte_em timestamptz;

create unique index if not exists cidades_codigo_ibge_unique
  on public.cidades (codigo_ibge)
  where codigo_ibge is not null;

create table if not exists public.congregacoes_cidades (
  id bigint generated by default as identity primary key,
  congregacao_id bigint not null references public.congregacoes(id) on delete restrict,
  cidade_id bigint not null references public.cidades(id) on delete restrict,
  ativada boolean not null default true,
  visivel_publico boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint congregacoes_cidades_unique unique (congregacao_id, cidade_id)
);

-- Preserva o vinculo antigo existente na propria cidade.
insert into public.congregacoes_cidades (congregacao_id, cidade_id)
select cidade.congregacao_id, cidade.id
from public.cidades cidade
where cidade.congregacao_id is not null
on conflict (congregacao_id, cidade_id) do nothing;

-- Acrescenta os vinculos reais encontrados nos territorios. Isso contempla,
-- por exemplo, uma mesma cidade utilizada por congregacoes diferentes.
insert into public.congregacoes_cidades (congregacao_id, cidade_id)
select distinct territorio.congregacao_id, territorio.cidade_id
from public.territorios territorio
where territorio.congregacao_id is not null
  and territorio.cidade_id is not null
on conflict (congregacao_id, cidade_id) do nothing;

do $$
begin
  if exists (
    select 1
    from public.territorios territorio
    where territorio.congregacao_id is not null
      and territorio.cidade_id is not null
      and not exists (
        select 1
        from public.congregacoes_cidades vinculo
        where vinculo.congregacao_id = territorio.congregacao_id
          and vinculo.cidade_id = territorio.cidade_id
      )
  ) then
    raise exception 'A migracao nao conseguiu preservar todos os vinculos entre territorios, congregacoes e cidades.';
  end if;
end
$$;

alter table public.congregacoes_cidades enable row level security;

grant select on public.congregacoes_cidades to anon, authenticated;
grant insert, update, delete on public.congregacoes_cidades to authenticated;
grant usage, select on sequence public.congregacoes_cidades_id_seq to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policy
    where polname = 'Vinculos publicos de cidades podem ser visualizados'
      and polrelid = 'public.congregacoes_cidades'::regclass
  ) then
    create policy "Vinculos publicos de cidades podem ser visualizados"
    on public.congregacoes_cidades
    for select
    to anon, authenticated
    using (ativada = true and visivel_publico = true);
  end if;

  if not exists (
    select 1 from pg_policy
    where polname = 'Administradores gerenciam cidades da congregacao'
      and polrelid = 'public.congregacoes_cidades'::regclass
  ) then
    create policy "Administradores gerenciam cidades da congregacao"
    on public.congregacoes_cidades
    for all
    to authenticated
    using (
      exists (
        select 1
        from public.usuarios_app usuario
        where usuario.auth_user_id = auth.uid()
          and usuario.ativo = true
          and (
            usuario.papel = 'superadmin'
            or (
              usuario.papel = 'admin'
              and usuario.congregacao_id = congregacoes_cidades.congregacao_id
            )
          )
      )
    )
    with check (
      exists (
        select 1
        from public.usuarios_app usuario
        where usuario.auth_user_id = auth.uid()
          and usuario.ativo = true
          and (
            usuario.papel = 'superadmin'
            or (
              usuario.papel = 'admin'
              and usuario.congregacao_id = congregacoes_cidades.congregacao_id
            )
          )
      )
    );
  end if;
end
$$;

-- Linha de base para conferir a integridade antes e depois da ativacao.
create table if not exists public.auditoria_migracoes (
  id bigint generated by default as identity primary key,
  nome_migracao text not null unique,
  executada_em timestamptz not null default now(),
  totais jsonb not null
);

alter table public.auditoria_migracoes enable row level security;
revoke all on public.auditoria_migracoes from anon, authenticated;

insert into public.auditoria_migracoes (nome_migracao, totais)
values (
  '20260901_preparar_multicongregacao_segura',
  jsonb_build_object(
    'congregacoes', (select count(*) from public.congregacoes),
    'cidades', (select count(*) from public.cidades),
    'territorios', (select count(*) from public.territorios),
    'enderecos', (select count(*) from public.enderecos),
    'publicadores', (select count(*) from public.publicadores),
    'grupos', (select count(*) from public.grupos),
    'bairros', (select count(*) from public.bairros),
    'congregacoes_cidades', (select count(*) from public.congregacoes_cidades)
  )
)
on conflict (nome_migracao) do nothing;

commit;
